In [1]:
import pandas as pd
import numpy as np

In [2]:
general_df = pd.read_csv('./generalizability/ldaMataveMetrics.csv')

In [3]:
general_df

,dataset,model,CHI,ZIPF,CLASSIFIER,IRPR,FID,PR,DC,MAUVE,TRADITIONAL,ZERO
0,yahoo,LDA,9.436303e-01,0.122554,0.888889,0.412986,1.012399,0.349915,0.103568,0.713425,0.374836,0.270910
1,yahoo,MATAVE,9.916591e-01,0.222275,0.962963,0.416155,1.028472,0.376042,0.096035,0.772034,0.562229,0.295235
2,yahoo,combinedTopicModel,9.995372e-01,0.158400,0.874558,0.414935,0.991504,0.214404,0.104635,0.720164,0.404874,0.252905
3,yahoo,realToReal,1.000000e+00,0.005036,0.416854,0.403372,0.880048,0.010016,0.029556,0.039246,0.148319,0.100081
4,yahoo,realToReal2,1.000000e+00,0.007992,0.593496,0.401987,0.865898,0.008375,0.012696,0.049415,0.155089,0.101293
5,yahoo,realToReal3,1.000000e+00,0.010083,0.373745,0.401627,0.868195,0.011692,0.014183,0.039774,0.177254,0.101734
6,banking77,LDA,2.776298e-13,0.131400,0.903989,0.310814,0.615170,0.382805,0.308852,0.703925,0.365555,0.147635
7,banking77,MATAVE,6.055634e-03,0.176033,0.991870,0.337082,0.716313,0.469054,0.637870,0.882104,0.445697,0.220855
8,banking77,combinedTopicModel,9.495060e-01,0.165787,0.934553,0.322378,0.623337,0.340998,0.442302,0.660813,0.396567,0.186324
9,banking77,realToReal,1.000000e+00,0.018521,0.609782,0.258443,0.365246,0.038515,0.007754,0.028652,0.154659,0.084253
10,banking77,realToReal2,1.000000e+00,0.015009,0.347368,0.255469,0.359308,0.025145,0.013050,0.028431,0.164521,0.079313
11,banking77,realToReal3,9.995537e-01,0.013292,0.490507,0.262185,0.368075,0.047055,0.006717,0.037632,0.152546,0.081038
12,medicalAbstracts,LDA,0.000000e+00,0.014930,0.821622,0.354773,0.708207,0.159788,0.034525,0.285763,0.501198,0.532371
13,medicalAbstracts,MATAVE,0.000000e+00,0.004101,0.905602,0.360913,0.972905,0.501161,0.197862,0.955450,0.533052,0.494359
14,medicalAbstracts,combinedTopicModel,0.000000e+00,0.004346,0.837463,0.354339,0.696929,0.163132,0.032745,0.189518,0.552586,0.519747
15,medicalAbstracts,realToReal,1.000000e+00,0.006567,0.452991,0.351541,0.616568,0.038377,0.022810,0.013975,0.160999,0.105775
16,medicalAbstracts,realToReal2,1.000000e+00,0.004054,0.455447,0.352545,0.611546,0.020187,0.028161,0.010134,0.206996,0.110598
17,medicalAbstracts,realToReal3,1.000000e+00,0.011087,0.449163,0.356777,0.629965,0.028568,0.035317,0.021185,0.188316,0.113702
18,dementiaAudio,LDA,0.000000e+00,0.275123,1.000000,0.268766,0.528872,0.971628,0.945400,0.994716,0.831707,0.291172
19,dementiaAudio,MATAVE,0.000000e+00,0.408289,1.000000,0.298694,0.678668,0.918791,0.985177,0.991864,0.742608,0.248349
20,dementiaAudio,combinedTopicModel,0.000000e+00,0.331092,1.000000,0.279785,0.554763,0.856502,0.953449,0.989917,0.760059,0.260540
21,dementiaAudio,realToReal,1.000000e+00,0.012869,0.502874,0.225210,0.246963,0.215590,0.067963,0.042560,0.185468,0.092006
22,dementiaAudio,realToReal2,1.000000e+00,0.012835,0.517491,0.224534,0.244026,0.221586,0.061010,0.052462,0.156498,0.080851
23,dementiaAudio,realToReal3,1.000000e+00,0.009173,0.556511,0.223291,0.244400,0.204767,0.005042,0.037800,0.193094,0.102939
24,huffPostNews,LDA,1.000000e+00,0.094843,0.903994,0.398165,0.932179,0.256034,0.113738,0.668309,0.408341,0.261322
25,huffPostNews,MATAVE,9.999413e-01,0.072751,0.933262,0.391973,0.914629,0.685871,0.069518,0.715154,0.596367,0.333143
26,huffPostNews,combinedTopicModel,1.000000e+00,0.074481,0.889925,0.399336,0.916891,0.350187,0.094235,0.708863,0.452646,0.263551
27,huffPostNews,realToReal,1.000000e+00,0.012715,0.485879,0.397893,0.825248,0.047104,0.056485,0.035705,0.158042,0.108758
28,huffPostNews,realToReal2,1.000000e+00,0.008621,0.514595,0.397513,0.816921,0.030260,0.042072,0.046989,0.182643,0.094002
29,huffPostNews,realToReal3,1.000000e+00,0.017338,0.429221,0.399145,0.822369,0.047402,0.059454,0.015851,0.152946,0.095095
30,clinc150,LDA,3.333420e-01,0.040010,0.905848,0.370837,0.903597,0.370109,0.267718,0.856025,0.297910,0.230938
31,clinc150,MATAVE,7.818290e-02,0.092056,0.908059,0.365799,0.918988,0.485963,0.192195,0.885654,0.287830,0.200108
32,clinc150,combinedTopicModel,2.151746e-01,0.025822,0.858749,0.369956,0.900922,0.393968,0.210487,0.850187,0.302133,0.212636
33,clinc150,realToReal,1.000000e+00,0.011899,0.513418,0.344821,0.705288,0.048500,0.033357,0.032981,0.149495,0.096747
34,clinc150,realToReal2,1.000000e+00,0.014937,0.569758,0.338226,0.702489,0.031744,0.026893,0.029132,0.151305,0.090212
35,clinc150,realToReal3,1.000000e+00,0.010114,0.596101,0.346390,0.713181,0.058700,0.043301,0.036017,0.166320,0.070286
36,syntheticCareHomeNurseNotes,LDA,1.776357e-15,0.014840,0.950396,0.313259,0.675701,0.687813,0.222372,0.774940,0.681963,0.241079
37,syntheticCareHomeNurseNotes,MATAVE,5.827899e-01,0.120457,0.832427,0.308065,0.544897,0.197927,0.224177,0.314331,0.475706,0.100687
38,syntheticCareHomeNurseNotes,combinedTopicModel,7.251117e-01,0.099836,0.889588,0.307831,0.537559,0.197901,0.126569,0.145305,0.513120,0.161325
39,syntheticCareHomeNurseNotes,realToReal,6.425657e-01,0.024013,0.532011,0.291150,0.419830,0.046790,0.039335,0.037413,0.156743,0.087810
40,syntheticCareHomeNurseNotes,realToReal2,6.666947e-01,0.019438,0.445422,0.291032,0.417973,0.033557,0.008770,0.043537,0.181092,0.086340
41,syntheticCareHomeNurseNotes,realToReal3,1.000000e+00,0.002707,0.459459,0.293564,0.423811,0.035180,0.029950,0.035616,0.150748,0.100210
42,clinicalDialogueSummarizations,LDA,1.804066e-02,0.067664,0.882244,0.324126,0.700172,0.346687,0.152044,0.670578,0.317777,0.289476
43,clinicalDialogueSummarizations,MATAVE,8.768662e-02,0.174165,0.884921,0.343103,0.754790,0.322953,0.491114,0.660508,0.373124,0.379120
44,clinicalDialogueSummarizations,combinedTopicModel,8.194380e-01,0.109620,0.844266,0.329221,0.692824,0.275295,0.224693,0.446787,0.330613,0.307443
45,clinicalDialogueSummarizations,realToReal,1.000000e+00,0.008507,0.433427,0.268679,0.471876,0.075303,0.043239,0.035384,0.180081,0.107883
46,clinicalDialogueSummarizations,realToReal2,1.000000e+00,0.007129,0.524975,0.263907,0.479710,0.081820,0.079033,0.070449,0.148069,0.107989
47,clinicalDialogueSummarizations,realToReal3,1.000000e+00,0.009529,0.523699,0.268450,0.478067,0.066987,0.085916,0.024512,0.176323,0.095942
48,simSUM,LDA,0.000000e+00,0.065586,0.948246,0.238410,0.453070,0.703834,0.914490,0.850609,0.487842,0.365717
49,simSUM,MATAVE,0.000000e+00,0.153250,0.975580,0.241777,0.516674,0.708391,0.899407,0.879122,0.506891,0.355691
50,simSUM,combinedTopicModel,0.000000e+00,0.126356,0.958913,0.237296,0.429561,0.684556,0.894699,0.608304,0.537282,0.344105
51,simSUM,realToReal,1.000000e+00,0.006168,0.543346,0.171518,0.146968,0.087157,0.020543,0.031643,0.158191,0.107454
52,simSUM,realToReal2,1.000000e+00,0.008202,0.552635,0.171034,0.148491,0.076661,0.027608,0.019644,0.137703,0.082215
53,simSUM,realToReal3,1.000000e+00,0.008179,0.491062,0.174633,0.157546,0.092484,0.015280,0.088886,0.151926,0.085165
54,atis,LDA,0.000000e+00,0.160100,0.924510,0.273549,0.499266,0.445983,0.649656,0.930024,0.391046,0.281507
55,atis,MATAVE,0.000000e+00,0.214378,0.965789,0.291243,0.556121,0.451170,0.812388,0.820226,0.367406,0.206154
56,atis,combinedTopicModel,0.000000e+00,0.194480,0.925578,0.278564,0.500423,0.381192,0.716741,0.879474,0.361791,0.232350
57,atis,realToReal,1.000000e+00,0.034241,0.492565,0.222348,0.246657,0.077028,0.109284,0.072197,0.157731,0.066055
58,atis,realToReal2,6.666748e-01,0.026406,0.570469,0.223348,0.249913,0.089978,0.015758,0.028859,0.162957,0.069030
59,atis,realToReal3,7.355493e-01,0.012060,0.478451,0.223697,0.236463,0.070448,0.016289,0.019121,0.160675,0.070581

In [4]:
calibrated_dfs = []
for dataset in general_df['dataset'].value_counts().keys().tolist():
    temp_df = general_df[general_df['dataset'] == dataset]
    temp_df = temp_df.drop(columns='dataset')

    # Get metric columns. 
    metric_cols = [c for c in temp_df.columns if 'model' not in c]
    # Extract real rows.
    real_mask = temp_df['model'].str.startswith('real')
    real_df = temp_df.loc[real_mask, metric_cols]

    # Get mean and standard deviation. 
    mean = real_df.mean()
    std_dev = real_df.std(ddof=1)
    # There should be a minimum standard deviation, otherwise the metric is returning all 0s or exhibits no variation (which we assume is not indicative of a perfect metric, but a failing one).
    min_std = 1e-4

    # Reliability is inverse standard deviation. 
    reliability = pd.Series(index=std_dev.index, dtype=float)

    for metric in std_dev.index:
        # Real-vs-real values for this metric
        real_values = real_df[metric]
        print(real_values)

        # Detect saturation at minimum or maximum
        all_zero = np.allclose(real_values, 0, atol=0.01)
        all_one = np.allclose(real_values, 1, atol=0.01)

        if all_zero or all_one:
            reliability[metric] = 0

        elif std_dev[metric] < min_std:
            reliability[metric] = 0

        else:
            reliability[metric] = 1 / std_dev[metric]

    if reliability.sum() == 0:
        raise ValueError(
            "All metrics were assigned zero reliability."
        )

    # Safe standard deviation for z-scoring.
    safe_std = std_dev.copy()
    safe_std[safe_std < min_std] = min_std


    weights = reliability / reliability.sum()
    weight_rank = weights.rank(ascending=False, method="dense").astype(int)
    
    # Calibrate scores.
    calibrated = temp_df.copy()

    for m in metric_cols:
        calibrated[m] = (
            (temp_df[m] - mean[m])
            / safe_std[m]
        )
        calibrated[f"rank_{m}"] = weight_rank[m]

    calibrated["final_score"] = (
        calibrated[metric_cols] * weights
    ).sum(axis=1)

    calibrated['dataset'] = dataset

    calibrated_dfs.append(calibrated)

3    1.0
4    1.0
5    1.0
Name: CHI, dtype: float64
3    0.005036
4    0.007992
5    0.010083
Name: ZIPF, dtype: float64
3    0.416854
4    0.593496
5    0.373745
Name: CLASSIFIER, dtype: float64
3    0.403372
4    0.401987
5    0.401627
Name: IRPR, dtype: float64
3    0.880048
4    0.865898
5    0.868195
Name: FID, dtype: float64
3    0.010016
4    0.008375
5    0.011692
Name: PR, dtype: float64
3    0.029556
4    0.012696
5    0.014183
Name: DC, dtype: float64
3    0.039246
4    0.049415
5    0.039774
Name: MAUVE, dtype: float64
3    0.148319
4    0.155089
5    0.177254
Name: TRADITIONAL, dtype: float64
3    0.100081
4    0.101293
5    0.101734
Name: ZERO, dtype: float64
9     1.000000
10    1.000000
11    0.999554
Name: CHI, dtype: float64
9     0.018521
10    0.015009
11    0.013292
Name: ZIPF, dtype: float64
9     0.609782
10    0.347368
11    0.490507
Name: CLASSIFIER, dtype: float64
9     0.258443
10    0.255469
11    0.262185
Name: IRPR, dtype: float64
9     0.365246
10    0.359308
11    0.368075
Name: FID, dtype: float64
9     0.038515
10    0.025145
11    0.047055
Name: PR, dtype: float64
9     0.007754
10    0.013050
11    0.006717
Name: DC, dtype: float64
9     0.028652
10    0.028431
11    0.037632
Name: MAUVE, dtype: float64
9     0.154659
10    0.164521
11    0.152546
Name: TRADITIONAL, dtype: float64
9     0.084253
10    0.079313
11    0.081038
Name: ZERO, dtype: float64
15    1.0
16    1.0
17    1.0
Name: CHI, dtype: float64
15    0.006567
16    0.004054
17    0.011087
Name: ZIPF, dtype: float64
15    0.452991
16    0.455447
17    0.449163
Name: CLASSIFIER, dtype: float64
15    0.351541
16    0.352545
17    0.356777
Name: IRPR, dtype: float64
15    0.616568
16    0.611546
17    0.629965
Name: FID, dtype: float64
15    0.038377
16    0.020187
17    0.028568
Name: PR, dtype: float64
15    0.022810
16    0.028161
17    0.035317
Name: DC, dtype: float64
15    0.013975
16    0.010134
17    0.021185
Name: MAUVE, dtype: float64
15    0.160999
16    0.206996
17    0.188316
Name: TRADITIONAL, dtype: float64
15    0.105775
16    0.110598
17    0.113702
Name: ZERO, dtype: float64
21    1.0
22    1.0
23    1.0
Name: CHI, dtype: float64
21    0.012869
22    0.012835
23    0.009173
Name: ZIPF, dtype: float64
21    0.502874
22    0.517491
23    0.556511
Name: CLASSIFIER, dtype: float64
21    0.225210
22    0.224534
23    0.223291
Name: IRPR, dtype: float64
21    0.246963
22    0.244026
23    0.244400
Name: FID, dtype: float64
21    0.215590
22    0.221586
23    0.204767
Name: PR, dtype: float64
21    0.067963
22    0.061010
23    0.005042
Name: DC, dtype: float64
21    0.042560
22    0.052462
23    0.037800
Name: MAUVE, dtype: float64
21    0.185468
22    0.156498
23    0.193094
Name: TRADITIONAL, dtype: float64
21    0.092006
22    0.080851
23    0.102939
Name: ZERO, dtype: float64
27    1.0
28    1.0
29    1.0
Name: CHI, dtype: float64
27    0.012715
28    0.008621
29    0.017338
Name: ZIPF, dtype: float64
27    0.485879
28    0.514595
29    0.429221
Name: CLASSIFIER, dtype: float64
27    0.397893
28    0.397513
29    0.399145
Name: IRPR, dtype: float64
27    0.825248
28    0.816921
29    0.822369
Name: FID, dtype: float64
27    0.047104
28    0.030260
29    0.047402
Name: PR, dtype: float64
27    0.056485
28    0.042072
29    0.059454
Name: DC, dtype: float64
27    0.035705
28    0.046989
29    0.015851
Name: MAUVE, dtype: float64
27    0.158042
28    0.182643
29    0.152946
Name: TRADITIONAL, dtype: float64
27    0.108758
28    0.094002
29    0.095095
Name: ZERO, dtype: float64
33    1.0
34    1.0
35    1.0
Name: CHI, dtype: float64
33    0.011899
34    0.014937
35    0.010114
Name: ZIPF, dtype: float64
33    0.513418
34    0.569758
35    0.596101
Name: CLASSIFIER, dtype: float64
33    0.344821
34    0.338226
35    0.346390
Name: IRPR, dtype: float64
33    0.705288
34    0.702489
35    0.713181
Name: FID, dtype: float64
33    0.048500
34    0.031744
35    0.058700
Name: PR, dtype: float64
33    0.033357
34    0.026893
35    0.043301
Name: DC, dtype: float64
33    0.032981
34    0.029132
35    0.036017
Name: MAUVE, dtype: float64
33    0.149495
34    0.151305
35    0.166320
Name: TRADITIONAL, dtype: float64
33    0.096747
34    0.090212
35    0.070286
Name: ZERO, dtype: float64
39    0.642566
40    0.666695
41    1.000000
Name: CHI, dtype: float64
39    0.024013
40    0.019438
41    0.002707
Name: ZIPF, dtype: float64
39    0.532011
40    0.445422
41    0.459459
Name: CLASSIFIER, dtype: float64
39    0.291150
40    0.291032
41    0.293564
Name: IRPR, dtype: float64
39    0.419830
40    0.417973
41    0.423811
Name: FID, dtype: float64
39    0.046790
40    0.033557
41    0.035180
Name: PR, dtype: float64
39    0.039335
40    0.008770
41    0.029950
Name: DC, dtype: float64
39    0.037413
40    0.043537
41    0.035616
Name: MAUVE, dtype: float64
39    0.156743
40    0.181092
41    0.150748
Name: TRADITIONAL, dtype: float64
39    0.08781
40    0.08634
41    0.10021
Name: ZERO, dtype: float64
45    1.0
46    1.0
47    1.0
Name: CHI, dtype: float64
45    0.008507
46    0.007129
47    0.009529
Name: ZIPF, dtype: float64
45    0.433427
46    0.524975
47    0.523699
Name: CLASSIFIER, dtype: float64
45    0.268679
46    0.263907
47    0.268450
Name: IRPR, dtype: float64
45    0.471876
46    0.479710
47    0.478067
Name: FID, dtype: float64
45    0.075303
46    0.081820
47    0.066987
Name: PR, dtype: float64
45    0.043239
46    0.079033
47    0.085916
Name: DC, dtype: float64
45    0.035384
46    0.070449
47    0.024512
Name: MAUVE, dtype: float64
45    0.180081
46    0.148069
47    0.176323
Name: TRADITIONAL, dtype: float64
45    0.107883
46    0.107989
47    0.095942
Name: ZERO, dtype: float64
51    1.0
52    1.0
53    1.0
Name: CHI, dtype: float64
51    0.006168
52    0.008202
53    0.008179
Name: ZIPF, dtype: float64
51    0.543346
52    0.552635
53    0.491062
Name: CLASSIFIER, dtype: float64
51    0.171518
52    0.171034
53    0.174633
Name: IRPR, dtype: float64
51    0.146968
52    0.148491
53    0.157546
Name: FID, dtype: float64
51    0.087157
52    0.076661
53    0.092484
Name: PR, dtype: float64
51    0.020543
52    0.027608
53    0.015280
Name: DC, dtype: float64
51    0.031643
52    0.019644
53    0.088886
Name: MAUVE, dtype: float64
51    0.158191
52    0.137703
53    0.151926
Name: TRADITIONAL, dtype: float64
51    0.107454
52    0.082215
53    0.085165
Name: ZERO, dtype: float64
57    1.000000
58    0.666675
59    0.735549
Name: CHI, dtype: float64
57    0.034241
58    0.026406
59    0.012060
Name: ZIPF, dtype: float64
57    0.492565
58    0.570469
59    0.478451
Name: CLASSIFIER, dtype: float64
57    0.222348
58    0.223348
59    0.223697
Name: IRPR, dtype: float64
57    0.246657
58    0.249913
59    0.236463
Name: FID, dtype: float64
57    0.077028
58    0.089978
59    0.070448
Name: PR, dtype: float64
57    0.109284
58    0.015758
59    0.016289
Name: DC, dtype: float64
57    0.072197
58    0.028859
59    0.019121
Name: MAUVE, dtype: float64
57    0.157731
58    0.162957
59    0.160675
Name: TRADITIONAL, dtype: float64
57    0.066055
58    0.069030
59    0.070581
Name: ZERO, dtype: float64

In [5]:
calibrated_results = pd.concat(calibrated_dfs)
calibrated_results

,model,CHI,ZIPF,CLASSIFIER,IRPR,FID,PR,DC,MAUVE,TRADITIONAL,...,rank_CLASSIFIER,rank_IRPR,rank_FID,rank_PR,rank_DC,rank_MAUVE,rank_TRADITIONAL,rank_ZERO,final_score,dataset
0,LDA,-563.697174,45.287521,3.671598,11.564781,18.570181,204.958881,9.079844,117.144949,14.180594,...,9,2,6,3,7,5,8,1,109.818583,yahoo
1,MATAVE,-83.408583,84.609292,4.307750,15.002829,20.686738,220.714097,8.272847,127.382847,26.562514,...,9,2,6,3,7,5,8,1,127.130506,yahoo
2,combinedTopicModel,-4.628214,59.422155,3.548525,13.679438,15.818661,123.243023,9.194088,118.322146,16.165381,...,9,2,6,3,7,5,8,1,92.169750,yahoo
3,realToReal,0.000000,-1.052020,-0.382261,1.132477,1.141413,-0.006836,1.151035,-0.622905,-0.786369,...,9,2,6,3,7,5,8,1,-0.102587,yahoo
4,realToReal2,0.000000,0.113771,1.134744,-0.370991,-0.721977,-0.996565,-0.655138,1.153469,-0.339085,...,9,2,6,3,7,5,8,1,-0.156367,yahoo
5,realToReal3,0.000000,0.938249,-0.752484,-0.761486,-0.419436,1.003400,-0.495896,-0.530564,1.125454,...,9,2,6,3,7,5,8,1,0.258954,yahoo
6,LDA,-3880.162110,43.444244,3.207581,15.487224,56.088133,31.321924,88.215020,128.074400,32.591137,...,9,3,5,8,4,6,7,1,50.279082,banking77
7,MATAVE,-3856.661772,60.190278,3.876452,23.293524,78.692933,39.131934,185.066338,162.015016,45.129464,...,9,3,5,8,4,6,7,1,81.226561,banking77
8,combinedTopicModel,-195.376544,56.346192,3.440207,18.923769,57.913300,27.536213,127.498001,119.862121,37.442921,...,9,3,5,8,4,6,7,1,61.508459,banking77
9,realToReal,0.577350,1.093215,0.968353,-0.076028,0.231627,0.145823,-0.417914,-0.556193,-0.404111,...,9,3,5,8,4,6,7,1,0.295052,banking77
10,realToReal2,0.577350,-0.224644,-1.028896,-0.959816,-1.095488,-1.064905,1.141165,-0.598253,1.138816,...,9,3,5,8,4,6,7,1,-0.330325,banking77
11,realToReal3,-1.154701,-0.868571,0.060543,1.035844,0.863861,0.919082,-0.723251,1.154445,-0.734706,...,9,3,5,8,4,6,7,1,0.035273,banking77
12,LDA,-10000.000000,2.158958,116.560738,0.414546,9.330945,14.360784,0.918283,48.244084,13.649577,...,2,1,8,7,6,5,9,4,42.129073,medicalAbstracts
13,MATAVE,-10000.000000,-0.879653,143.082519,2.623999,37.130355,51.856648,26.946640,167.610547,15.026525,...,2,1,8,7,6,5,9,4,63.467240,medicalAbstracts
14,combinedTopicModel,-10000.000000,-0.811009,121.563566,0.258148,8.146523,14.728011,0.634549,31.089057,15.870916,...,2,1,8,7,6,5,9,4,40.358034,medicalAbstracts
15,realToReal,0.000000,-0.187820,0.144517,-0.748509,-0.293162,1.025106,-0.948589,-0.200145,-1.056397,...,2,1,8,7,6,5,9,4,-0.384770,medicalAbstracts
16,realToReal2,0.000000,-0.892772,0.919879,-0.387192,-0.820653,-0.972844,-0.095911,-0.884791,0.931954,...,2,1,8,7,6,5,9,4,-0.215933,medicalAbstracts
17,realToReal3,0.000000,1.080593,-1.064396,1.135701,1.113815,-0.052262,1.044500,1.084936,0.124444,...,2,1,8,7,6,5,9,4,0.600703,medicalAbstracts
18,LDA,-10000.000000,124.040024,17.107979,45.640994,177.492603,88.878935,26.111061,127.067941,33.839071,...,8,1,2,5,9,4,7,6,96.233720,dementiaAudio
19,MATAVE,-10000.000000,186.727496,17.107979,76.390594,271.196268,82.680667,27.264134,126.686627,29.224402,...,8,1,2,5,9,4,7,6,142.081177,dementiaAudio
20,combinedTopicModel,-10000.000000,150.387361,17.107979,56.962454,193.688368,75.373502,26.344368,126.426236,30.128192,...,8,1,2,5,9,4,7,6,108.649647,dementiaAudio
21,realToReal,0.000000,0.585474,-0.820501,0.888767,1.146774,0.188778,0.675187,-0.229121,0.368493,...,8,1,2,5,9,4,7,6,0.738661,dementiaAudio
22,realToReal2,0.000000,0.569188,-0.293371,0.194029,-0.690358,0.892157,0.473635,1.094677,-1.131959,...,8,1,2,5,9,4,7,6,0.054270,dementiaAudio
23,realToReal3,0.000000,-1.154662,1.113872,-1.082796,-0.456416,-1.080934,-1.148822,-0.865556,0.763466,...,8,1,2,5,9,4,7,6,-0.792932,dementiaAudio
24,LDA,-0.000042,18.790002,9.838899,-0.022159,26.167081,21.856224,6.567964,40.310115,15.352127,...,9,1,2,6,5,7,8,4,9.231339,huffPostNews
25,MATAVE,-0.586933,13.724703,10.512605,-7.276941,22.017423,65.665039,1.812015,43.281709,27.192298,...,9,1,2,6,5,7,8,4,7.023048,huffPostNews
26,combinedTopicModel,0.000000,14.121439,9.515040,1.350439,22.552301,31.452254,4.470340,42.882653,18.142052,...,9,1,2,6,5,7,8,4,9.608989,huffPostNews
27,realToReal,0.000000,-0.040497,0.214401,-0.340353,0.883247,0.562122,0.410265,0.181239,-0.409419,...,9,1,2,6,5,7,8,4,0.015580,huffPostNews
28,realToReal2,0.000000,-0.979136,0.875411,-0.785396,-1.085755,-1.154568,-1.139885,0.896986,1.139740,...,9,1,2,6,5,7,8,4,-0.741787,huffPostNews
29,realToReal3,0.000000,1.019633,-1.089811,1.125750,0.202508,0.592446,0.729620,-1.078225,-0.730321,...,9,1,2,6,5,7,8,4,0.726207,huffPostNews
30,LDA,-6666.579610,11.356319,8.193591,6.392001,35.460604,23.790623,28.213822,238.624108,15.396764,...,9,3,4,7,5,2,6,8,59.253195,clinc150
31,MATAVE,-9218.170979,32.699620,8.245935,5.229036,38.236670,32.302909,19.076670,247.211348,14.305357,...,9,3,4,7,5,2,6,8,66.348507,clinc150
32,combinedTopicModel,-7848.253980,5.538247,7.078538,6.188752,34.978132,25.543651,21.289680,236.931977,15.853992,...,9,3,4,7,5,2,6,8,56.741781,clinc150
33,realToReal,0.000000,-0.171228,-1.097121,0.386692,-0.306177,0.160591,-0.140344,0.078589,-0.672586,...,9,3,4,7,5,2,6,8,-0.039395,clinc150
34,realToReal2,0.000000,1.074558,0.236720,-1.135605,-0.811117,-1.070577,-0.922414,-1.036976,-0.476555,...,9,3,4,7,5,2,6,8,-0.318580,clinc150
35,realToReal3,0.000000,-0.903330,0.860401,0.748913,1.117294,0.909986,1.062758,0.958387,1.149141,...,9,3,4,7,5,2,6,8,0.357975,clinc150
36,LDA,-3.853314,-0.048692,10.144305,14.936800,85.557287,89.968536,12.540592,177.245085,32.301404,...,9,1,2,4,7,3,8,5,55.870703,syntheticCareHomeNurseNotes
37,MATAVE,-0.935922,9.367771,7.605827,11.302070,41.698043,22.089216,12.655896,66.333074,19.466905,...,9,1,2,4,7,3,8,5,24.669561,syntheticCareHomeNurseNotes
38,combinedTopicModel,-0.223472,7.529285,8.835822,11.138295,39.237470,22.085624,6.421903,25.632428,21.795025,...,9,1,2,4,7,3,8,5,19.028686,syntheticCareHomeNurseNotes
39,realToReal,-0.636690,0.769189,1.141456,-0.535342,-0.237352,1.147381,0.850505,-0.347273,-0.380713,...,9,1,2,4,7,3,8,5,-0.179607,syntheticCareHomeNurseNotes
40,realToReal2,-0.515903,0.361235,-0.721752,-0.618363,-0.859970,-0.686107,-1.101626,1.127340,1.134440,...,9,1,2,4,7,3,8,5,-0.345997,syntheticCareHomeNurseNotes
41,realToReal3,1.152593,-1.130424,-0.419704,1.153705,1.097322,-0.461274,0.251121,-0.780067,-0.753726,...,9,1,2,4,7,3,8,5,0.525604,syntheticCareHomeNurseNotes
42,LDA,-9819.593449,49.196731,7.395803,21.219789,54.131692,36.583463,3.607141,26.123077,8.550559,...,8,1,2,4,6,7,5,3,30.030351,clinicalDialogueSummarizations
43,MATAVE,-9123.133845,137.588386,7.446802,28.270390,67.352963,33.391100,18.405639,25.703612,11.713556,...,8,1,2,4,6,7,5,3,37.686956,clinicalDialogueSummarizations
44,combinedTopicModel,-1805.620054,84.018708,6.672280,23.112911,52.352832,26.980767,6.777859,16.801070,9.284126,...,8,1,2,4,6,7,5,3,29.208776,clinicalDialogueSummarizations
45,realToReal,0.000000,0.098621,-1.154615,0.619368,-1.131639,0.080664,-1.141602,-0.335904,0.681376,...,8,1,2,4,6,7,5,3,0.002301,clinicalDialogueSummarizations
46,realToReal2,0.000000,-1.045657,0.589470,-1.153655,0.764679,0.957225,0.420605,1.124705,-1.148026,...,8,1,2,4,6,7,5,3,-0.018461,clinicalDialogueSummarizations
47,realToReal3,0.000000,0.947035,0.565145,0.534287,0.366960,-1.037889,0.720997,-0.788801,0.466650,...,8,1,2,4,6,7,5,3,0.016160,clinicalDialogueSummarizations
48,LDA,-10000.000000,49.720125,12.629676,33.796271,52.823981,76.812668,144.412638,21.725222,32.248963,...,7,1,2,4,3,8,5,6,54.197194,simSUM
49,MATAVE,-10000.000000,124.779795,13.453145,35.519526,63.946587,77.378698,141.974299,22.495811,34.063413,...,7,1,2,4,3,8,5,6,56.426083,simSUM
50,combinedTopicModel,-10000.000000,101.752045,12.951049,33.225724,48.712896,74.418150,141.213319,15.176864,36.958170,...,7,1,2,4,3,8,5,6,52.812830,simSUM
51,realToReal,0.000000,-1.154644,0.431741,-0.448833,-0.705391,0.214008,-0.097132,-0.407579,0.849429,...,7,1,2,4,3,8,5,6,-0.147092,simSUM
52,realToReal2,0.000000,0.587179,0.711599,-0.696947,-0.439023,-1.089679,1.045022,-0.731844,-1.102101,...,7,1,2,4,3,8,5,6,-0.461488,simSUM
53,realToReal3,0.000000,0.567465,-1.143340,1.145781,1.144414,0.875671,-0.947890,1.139423,0.252672,...,7,1,2,4,3,8,5,6,0.608580,simSUM
54,LDA,-4.550553,12.078337,8.287009,72.034153,36.329755,36.917473,11.190359,31.497704,88.006386,...,8,1,4,5,9,7,3,2,70.823910,atis
55,MATAVE,-4.550553,16.903704,9.119978,97.313948,44.432442,37.439491,14.212583,27.611711,78.983950,...,8,1,4,5,9,7,3,2,78.353926,atis
56,combinedTopicModel,-4.550553,15.134715,8.308573,79.198815,36.494658,30.397069,12.436239,29.708607,76.841002,...,8,1,4,5,9,7,3,2,69.425764,atis
57,realToReal,1.132372,0.889455,-0.429073,-1.118226,0.329598,-0.213703,1.154687,1.137425,-1.039391,...,8,1,4,5,9,7,3,2,-0.866728,atis
58,realToReal2,-0.761890,0.192965,1.142934,0.309757,0.793598,1.089576,-0.582273,-0.396380,0.955298,...,8,1,4,5,9,7,3,2,0.425538,atis
59,realToReal3,-0.370482,-1.082420,-0.713861,0.808469,-1.123195,-0.875874,-0.572414,-0.741045,0.084093,...,8,1,4,5,9,7,3,2,0.441190,atis

In [6]:
calibrated_results.to_csv('./generalizability.csv')

In [7]:
ranked_dict_results = []
for dataset in calibrated_results['dataset'].unique():
    subset = calibrated_results[calibrated_results['dataset'] == dataset]
    # Extract not real rows.
    real_mask = subset['model'].str.startswith('real')
    subset = subset.loc[~real_mask]
    ranks = subset['final_score'].rank(
        ascending=True,
        method='dense'
    ).astype(int)
    ranked_dict_results.append(pd.DataFrame({
        'model': subset['model'].values,
        'dataset': dataset,
        'final_score': subset['final_score'].values,
        'rank': ranks.values
    }))

In [8]:
ranked_results_df = pd.concat(ranked_dict_results)
ranked_results_df

                model                         dataset  final_score  rank
0                 LDA                           yahoo   109.818583     2
1              MATAVE                           yahoo   127.130506     3
2  combinedTopicModel                           yahoo    92.169750     1
0                 LDA                       banking77    50.279082     1
1              MATAVE                       banking77    81.226561     3
2  combinedTopicModel                       banking77    61.508459     2
0                 LDA                medicalAbstracts    42.129073     2
1              MATAVE                medicalAbstracts    63.467240     3
2  combinedTopicModel                medicalAbstracts    40.358034     1
0                 LDA                   dementiaAudio    96.233720     1
1              MATAVE                   dementiaAudio   142.081177     3
2  combinedTopicModel                   dementiaAudio   108.649647     2
0                 LDA                    huffPostNews     9.231339     2
1              MATAVE                    huffPostNews     7.023048     1
2  combinedTopicModel                    huffPostNews     9.608989     3
0                 LDA                        clinc150    59.253195     2
1              MATAVE                        clinc150    66.348507     3
2  combinedTopicModel                        clinc150    56.741781     1
0                 LDA     syntheticCareHomeNurseNotes    55.870703     3
1              MATAVE     syntheticCareHomeNurseNotes    24.669561     2
2  combinedTopicModel     syntheticCareHomeNurseNotes    19.028686     1
0                 LDA  clinicalDialogueSummarizations    30.030351     2
1              MATAVE  clinicalDialogueSummarizations    37.686956     3
2  combinedTopicModel  clinicalDialogueSummarizations    29.208776     1
0                 LDA                          simSUM    54.197194     2
1              MATAVE                          simSUM    56.426083     3
2  combinedTopicModel                          simSUM    52.812830     1
0                 LDA                            atis    70.823910     2
1              MATAVE                            atis    78.353926     3
2  combinedTopicModel                            atis    69.425764     1

In [9]:
ranked_results_df[ranked_results_df['rank'] == 1]['model'].value_counts()

model
combinedTopicModel    7
LDA                   2
MATAVE                1
Name: count, dtype: int64